/**
 * graph.ts
 * Builds the unified multi-modal transit graph from the pre-processed JSON/CSV data.
 * Imports transfer_edges.json (generated by build_interchange_nodes.py).
 *
 * Edge types in the graph:
 *   in-vehicle     → between consecutive stops on the same route
 *   transfer-walk  → between stops of different modes within walking distance
 *   transfer-wait  → penalty at an interchange node (headway / 2)
 *
 * Usage:
 *   import { buildGraph } from "./graph";
 *   const graph = buildGraph(stopsData, routeStopsData, segmentTimesData, transferEdgesData);
 */

import type { Stop, RouteStop, SegmentTime, GraphEdge, AgencyId } from "./types";

// Average headway in minutes per mode (used for transfer-wait penalty)
const AVG_HEADWAY_MINS: Record<AgencyId, number> = {
  metro: 8,
  brt: 10,
  municipal_bus: 20,
};

export interface TransitGraph {
  /** Adjacency list: node_id → array of outgoing edges */
  adjacency: Map<string, GraphEdge[]>;
  /** Quick stop lookup */
  stops: Map<string, Stop>;
}

/**
 * Build the full unified transit graph.
 * All time weights are in **seconds** for Dijkstra precision.
 */
export function buildGraph(
  stops: Stop[],
  routeStops: RouteStop[],
  segmentTimes: SegmentTime[],
  transferEdges: GraphEdge[],
): TransitGraph {
  const adjacency = new Map<string, GraphEdge[]>();
  const stopMap = new Map<string, Stop>(stops.map((s) => [s.stop_id, s]));

  // Helper: add an edge (one direction only)
  function addEdge(edge: GraphEdge) {
    const bucket = adjacency.get(edge.from_id) ?? [];
    bucket.push(edge);
    adjacency.set(edge.from_id, bucket);
  }

  // ── Build a segment time lookup ─────────────────────────────────────────────
  const segTimeMap = new Map<string, number>(); // "from_id|to_id" → seconds
  for (const seg of segmentTimes) {
    segTimeMap.set(
      `${seg.from_stop_id}|${seg.to_stop_id}`,
      Math.round(seg.median_minutes * 60),
    );
  }

  // ── In-vehicle edges (consecutive stops on same route) ──────────────────────
  // Group route stops by route_id, sorted by stop_sequence
  const byRoute = new Map<string, RouteStop[]>();
  for (const rs of routeStops) {
    const arr = byRoute.get(rs.route_id) ?? [];
    arr.push(rs);
    byRoute.set(rs.route_id, arr);
  }

  for (const [routeId, stops] of byRoute) {
    const sorted = stops.slice().sort((a, b) => a.stop_sequence - b.stop_sequence);
    for (let i = 0; i < sorted.length - 1; i++) {
      const from = sorted[i];
      const to = sorted[i + 1];
      const agency = from.agency;

      // Prefer actual segment time; fall back to mode-based speed estimate
      const lookupKey = `${from.stop_id}|${to.stop_id}`;
      const knownSecs = segTimeMap.get(lookupKey);

      let weightSecs: number;
      if (knownSecs !== undefined) {
        weightSecs = knownSecs;
      } else {
        // Haversine fallback using average speed per mode
        const fromStop = stopMap.get(from.stop_id);
        const toStop = stopMap.get(to.stop_id);
        if (fromStop && toStop) {
          const dist = haversine(fromStop.lat, fromStop.lon, toStop.lat, toStop.lon);
          const speedMps = agencySpeedMps(agency);
          weightSecs = Math.round(dist / speedMps);
        } else {
          weightSecs = 120; // 2 min default
        }
      }

      // Add both directions (in-vehicle is bidirectional on all Ahmedabad modes)
      addEdge({
        from_id: from.stop_id,
        to_id: to.stop_id,
        type: "in-vehicle",
        weight_secs: weightSecs,
        agency,
        route_id: routeId,
      });
      addEdge({
        from_id: to.stop_id,
        to_id: from.stop_id,
        type: "in-vehicle",
        weight_secs: weightSecs,
        agency,
        route_id: routeId,
      });
    }
  }

  // ── Transfer-walk edges ─────────────────────────────────────────────────────
  for (const te of transferEdges) {
    // transfer-wait penalty: add headway/2 for the boarding mode
    const boardMode = (te as any).to_mode as AgencyId | undefined;
    const waitSecs = boardMode
      ? Math.round((AVG_HEADWAY_MINS[boardMode] ?? 10) * 30) // headway/2 in secs
      : 0;

    addEdge({
      ...te,
      type: "transfer-walk",
      // total weight = walk + wait
      weight_secs: te.weight_secs + waitSecs,
    });
  }

  return { adjacency, stops: stopMap };
}

// ── Utilities ──────────────────────────────────────────────────────────────────

export function haversine(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6_371_000;
  const phi1 = (lat1 * Math.PI) / 180;
  const phi2 = (lat2 * Math.PI) / 180;
  const dPhi = ((lat2 - lat1) * Math.PI) / 180;
  const dLam = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dPhi / 2) ** 2 +
    Math.cos(phi1) * Math.cos(phi2) * Math.sin(dLam / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

function agencySpeedMps(agency: AgencyId): number {
  switch (agency) {
    case "metro": return 34_000 / 3600; // 34 km/h
    case "brt":  return 20_000 / 3600; // 20 km/h
    case "municipal_bus":  return 15_000 / 3600; // 15 km/h
  }
}
